dependencies:
  - name: postgresql
    version: 8.6.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 9.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
